TRAIN_DATAPATH = 'D:\\emb\\data\\fashion_iq\\dress\\dataframe\\train_3.csv'
VALID_DATAPATH = 'D:\\emb\\data\\fashion_iq\\dress\\dataframe\\valid_3.csv'
TEST_DATAPATH = 'D:\\emb\\data\\fashion_iq\\dress\\dataframe\\test_3.csv'
IMAGES_DATAPATH = 'D:\\emb\\data\\fashion_iq\\dress\\images'
PATH_SEPARATOR = '\\'